export const STRINGS = {
  ADD: "Agregar",
  CANCEL: "Cancelar",
  CONTROL_VERSIONS_ARIA: "control-versions",
  CREATE: "Crear",
  DEFAULT_VERSION_NAME: "Versión 1",
  DELETE: "Eliminar",
  DELETING: "Eliminando",
  DELETING_UPPER: "ELIMINANDO",
  DRAG_PROJECT: "Arrastrar",
  DROP_PROJECT: "Soltar",
  EDIT: "Editar",
  ERROR_FETCHING_NAME: "Error obteniendo nombre",
  ERROR_GENERIC: "Error",
  FILE_INVALID_FORMAT: "Formato incorrecto",
  FILE_READ_ERROR: "Error de lectura",
  FORM_EDITOR: "Editor de Formas Precodificadas",
  FULL_SCREEN: "Pantalla completa",
  NEW: "Nueva",
  NEW_PROJECT: "Nueva forma",
  NEW_VERSION: "Nueva versión",
  NO_DATA_ALT: "no-data-img",
  NO_DATA_MESSAGE: "Sin contenido para mostrar",
  OPEN_DRAWER_ARIA: "open drawer",
  PRECODED_FORM_NAME: "Forma precodificada",
  PRINT: "PDF",
  PROJECT_NAME_LABEL: "Nombre",
  PROJECT_NAME_PLACEHOLDER: "Nombre",
  RETRY: "Reintentar",
  SAVE_LOWER: "Guardar",
  SAVING_LOWER: "Guardando",
  SIRECAT_SUBTITLE: "Sistema de Información Registral y de Catastro e Información Territorial",
  SIRECAT_TITLE: "SIReCaT",
  SUBMIT: "Enviar",
  TXT_FILES_ONLY: "Formato permitido: .txt (5 MB)",
  GITLAB_EDITOR: "EDITOR DE HISTORIAS DE USUARIO"
} as const;
